### PR TITLE
Create the qgis-server-admin user with its SSH config

### LINKED ISSUE #21: [qgis4] Create the qgis-server-admin user as part of the Ansible process
Today the QGIS Server CertifSuite WFS 1.1.0 failed because we forgot to add SSH keys for the new qgis-server-admin user. As discussed with @pblottiere we think that the creation of the qgis-server-admin user should be handled by the Ansible process.

More specifically the Ansible process should:

1. create the qgis-server-admin user
2. create her SSH config (`~/.ssh/config`)
3. add her SSH keys

We'll need to use git-encrypt to encrypt the SSH private key in the Git repo.

### PR DESCRIPTION
**Pull request by elemoine**
@pblottiere this addresses #21.

Closes #21.

### CODE REVIEW

**Comment by elemoine** [comment]
@pblottiere I added you blottiere.paul@gmail.com GPG key. Before we merge please check that you can use git-crypt and actually decrypt the qgis4/ansible/roles/base/files/id_rsa_qgis_foundation file that is encrypted using our GPG public keys.

**Comment by pblottiere** [comment]
> I added you blottiere.paul@gmail.com GPG key. 

@elemoine Awesome, thanks!

> Before we merge please check that you can use git-crypt and actually decrypt the qgis4/ansible/roles/base/files/id_rsa_qgis_foundation file that is encrypted using our GPG public keys.

Yes, I take a look asap.

**Comment by elemoine** [comment]
Kind reminder on this one @pblottiere :-)

**Comment by pblottiere** [comment]
I have just tested and it works great, thanks @elemoine :+1:.

> Kind reminder on this one @pblottiere :-)

You did well :)!

**Pull request merged**
